---
#
#
# Author: John McDonough (jomcdono@cisco.com)
#         Cisco Systems, Inc.
#
# get_ucsm_sel.yml
#
# This UCS Ansible playbook does not require UCS Ansible modules it works
# purley with the Ansible uri and xml modules. A UCS token is retrived and
# used in the header of successive GET requests to pull Server SEL logs
# from UCS Manager.

# GET UCS SEL
- name: GET UCS SEL
  hosts: ucs
  connection: local
  gather_facts: no

  tasks:
  - name: Get UCS auth token (cookie)
    uri: 
      url: "http://{{hostname}}/nuova"
      method: POST
      return_content: yes
      headers:
        Content_type: "text/xml"
      body: '<aaaLogin inName="{{username}}" inPassword="{{password}}" />'
    register: login
  
  - name: Show response
    debug:
        msg: "{{login.content}}"

  - name: Extract auth token (cookie)
    xml:
      xmlstring: "{{login.content}}"
      xpath: /aaaLogin
      content: attribute
    register: cookie

  - name: Show cookie
    debug:
        msg: "{{cookie.matches.0.aaaLogin.outCookie}}"

  - uri: 
      url: "http://{{hostname}}/ucsm/../operations/server-{{server_id}}/sel.txt"
      method: GET
      return_content: yes
      headers:
        Content_type: "text/xml"
        Cookie: 'ucsm-cookie="{{cookie.matches.0.aaaLogin.outCookie}}"'
    register: sel

  - name: Show response
    debug:
        msg: "{{sel}}"
